/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Alguma2UiModule extends AbstractAlguma2UiModule {

	public Alguma2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
