/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2.ide;


/**
 * Use this class to register ide components.
 */
public class Alguma2IdeModule extends AbstractAlguma2IdeModule {
}
