/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2.ui.tests;

import com.google.inject.Injector;
import com.mycompany.alguma2.ui.internal.Alguma2Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class Alguma2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Alguma2Activator.getInstance().getInjector("com.mycompany.alguma2.Alguma2");
	}

}
