/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma.ui;

import com.google.inject.Injector;
import com.mycompany.alguma.ui.internal.AlgumaActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlgumaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AlgumaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AlgumaActivator activator = AlgumaActivator.getInstance();
		return activator != null ? activator.getInjector(AlgumaActivator.COM_MYCOMPANY_ALGUMA_ALGUMA) : null;
	}

}
