/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class AlgumaProposalProvider extends AbstractAlgumaProposalProvider {
}
