/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Alguma2RuntimeModule extends AbstractAlguma2RuntimeModule {
}
