/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Alguma2AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/mycompany/alguma2/parser/antlr/internal/InternalAlguma2.tokens");
	}
}
