/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.mycompany.alguma.AlgumaRuntimeModule;
import com.mycompany.alguma.AlgumaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlgumaIdeSetup extends AlgumaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlgumaRuntimeModule(), new AlgumaIdeModule()));
	}
	
}
