/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma.ide;


/**
 * Use this class to register ide components.
 */
public class AlgumaIdeModule extends AbstractAlgumaIdeModule {
}
