/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AlgumaUiModule extends AbstractAlgumaUiModule {

	public AlgumaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
