/*
 * generated by Xtext 2.31.0
 */
package com.mycompany.alguma2.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractAlguma2ScopeProvider extends XbaseBatchScopeProvider {
}
